This is the most versatile way I found to have a system that doesn't move with
the changes to my ArchLinux workstation (compiler, glibc, etc.), while at the
same time being able to create new environments and to install new packages with
Spack.

* Build

#+begin_example
sudo -E apptainer build dev_envs.sif dev_envs.def
#+end_example
(this is very quick to create, and if I add new environments to the Spack
overlay, we can just modify it quickly and add references to those new environments)

#+begin_example
./create_spack_overlay.sh
#+end_example
(this just creates a persistent overlay, tied to =/spack=, writable as a regular
user, so that I can have a complete Spack installation. The variables
=SPACK_ROOT=, =SPACK_USER_CONFIG_PATH=, =SPACK_USER_CACHE_PATH= (see =.def=
file) guarantee that this Spack installation is independent of my host Spack
installation).

#+begin_example
apptainer shell --overlay spack.img dev_envs.sif
Apptainer>  . inside_appt.sh
#+end_example
(this installs the spack environments, based on the .yaml files. See the %help
section in the .def file for instructions on how to use it).

+ Built on =[2023-03-07 Tue]=:
  + Ubuntu 22.04
  + Apptainer 1.1.5
  + Spack 0.19.1
  + gcc: 10.4.0 ; 9.5.0
  + Notes, when building there are errors for both environments about python
    installation [Bus error (core dumped)], but it seems OK if I install it with
    just -j 1 

* Running

Just run =envs/gcc_9_5_0.sh= or =envs/gcc_10_4_0.sh= and we end up in one of
these environments, where we can actually add other software if we want, since
the overlay is writable by my regular user.


* NOTE                                                             :noexport:

On [2023-06-29 Thu], moving to siehp I will try to no use these environments,
which were always a bit messy, running inside the container, not having access
to everything in the computer, etc. so I delete the apptainer images and
overlays as to free up space, but I leave the notes here, in case I want to
recreate them in the future.
